config/routes.rb
Rails.application.routes.draw do


  # Public routes
  devise_for :users, :path => "applicant", controllers: {registrations: 'registrations'}, path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :apply

  # Admin routes
  devise_for :admins, :path => "admin", path_names: {sign_in: 'login', sign_out: 'logout'}
  scope '/admin' do

    resources :cohorts
    resources :admission_applications do
      member do
        patch 'workflow/:workflow_action', to: 'admission_applications#workflow', as: 'workflow'
      end
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :courses do
      resources :logic_questions, :profile_questions, except: :index
    end


    resources :admins, path: 'employees' do
      member do
        patch 'update_password'
        get 'edit_password'
      end
    end

    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/index', to: 'dashboard#index'
    get 'dashboard/chart/:type(/:time_filter)', to: 'dashboard#chart', as: 'dashboard_chart_data'

    get 'cohort/chart/:cohort_id/:type(/:time_filter)', to: 'cohorts#chart', as: 'cohort_chart_data'

    authenticated :admin do
      mount DelayedJobWeb, :at => "/delayed_job", via: [:get, :post]
    end

    # For testing various features
    get 'testing/timeout', to: 'testing#timeout'
    get 'testing/email', to: 'testing#email'
    get 'ping', to: 'testing#ping'

    root 'dashboard#index', as: :admin_root_path
  end

  get '/launch', to: 'home#launch'
  get '/live', to: 'home#live'
  get '/jobs', to: 'home#jobs'
  get '/volunteer', to: 'home#volunteer', as: 'volunteer'
  get '/catalog', to: redirect('/assets/documents/catalog.pdf')
  get '/conduct', to: redirect('/assets/documents/conduct_guide.pdf')
  get '/program', to: redirect('/assets/documents/program_description.pdf')

  root 'home#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < AdminApplicationController
  require('groupdate')

  def index
    @user_count = User.count
    @apps_count = AdmissionApplication.started.count
    @apps_completed_count = AdmissionApplication.all_completed.count
    @apps_accepted_count = AdmissionApplication.accepted.count
    @app_line_time_filter = set_apps_time_filter
    @user_filter_count = User.where('created_at > ?', @time_filter).count
    @apps_started_filter_count = AdmissionApplication.started.where('created_at > ?', @time_filter).count
    @apps_completed_filter_count = AdmissionApplication.all_completed.where('completed_at > ?', @time_filter).count
    @cohorts = Cohort.active
    @cohorts_active_count = Cohort.active.count
    @cohorts_target_count = Cohort.active.sum(:target_size)
    @cohorts_accepted_count = AdmissionApplication.where(assigned_cohort: @cohorts).count
    @cohorts_confirmed_count = AdmissionApplication.where(assigned_cohort: @cohorts).where(application_status: 'confirmed').count
    @cohorts_accepted_pct = @cohorts_target_count == 0 ? 0 : @cohorts_accepted_count.fdiv(@cohorts_target_count) * 100
    @cohorts_confirmed_pct = @cohorts_target_count == 0 ? 0 : @cohorts_confirmed_count.fdiv(@cohorts_target_count) * 100
  end

  def chart
    case params[:type]
      when 'referral_source'
        render json: AdmissionApplication.has_referral.group(:referral_source).count
      when 'education'
        render json: AdmissionApplication.has_referral.group(:education).count
      when 'payment_option'
        render json: AdmissionApplication.all_completed.group(:payment_option).count
      when 'created_and_completed'
        set_apps_time_filter
        @new_users_date60 = AdmissionApplication.group_by_day(:created_at, range: @time_filter..DateTime.now, format: "%m/%d/%Y").count
        @apps_by_create_date60 = AdmissionApplication.started.group_by_day(:created_at, range: @time_filter..DateTime.now, format: "%m/%d/%Y").count
        @apps_by_completed_date60 = AdmissionApplication.all_completed.group_by_day(:completed_at, range: @time_filter..DateTime.now, format: "%m/%d/%Y").count
        @new_users_date60 = convert_to_area @new_users_date60
        @apps_by_create_date60 = convert_to_area @apps_by_create_date60
        @apps_by_completed_date60 = convert_to_area @apps_by_completed_date60

        render json: merge_started_and_complete
    end
  end

  def set_display_page_header
    @display_page_header = false
  end

  private
  def merge_started_and_complete
    [
        {name: "New Users", data: @new_users_date60},
        {name: "Started", data: @apps_by_create_date60},
        {name: "Completed", data: @apps_by_completed_date60}
    ]
  end

  def set_apps_time_filter
    if params[:apps_time_filter].blank?
      filter = cookies[:dashboard_apps_time_filter].blank? ? 'quarter' : cookies[:dashboard_apps_time_filter]
    else
      cookies[:dashboard_apps_time_filter] = params[:apps_time_filter]
      filter = params[:apps_time_filter]
    end
    @time_filter = 90.days.ago.midnight
    @time_filter_days = 90
    case filter
      when 'week'
        @time_filter = 1.week.ago.midnight
        @time_filter_days = 7
      when 'month'
        @time_filter =  1.month.ago.midnight
        @time_filter_days = (Date.today - 1.month.ago.to_date).to_i
      when 'year'
        @time_filter = 1.year.ago.midnight
        @time_filter_days = 365
    end
    filter
  end

  def convert_to_area(original_val)
    val = Hash.new
    cnt = 0
    original_val.each do |key,value|
      cnt += value.to_i
      val[key] = cnt
    end
    val
  end

end

app/views/dashboard/index.html.erb
<% content_for :page_title, 'Dashboard' %>

<div class="row">
  <div class="col-md-3 col-sm-6">
    <div class="ibox">
      <div class="ibox-title"><h5>Users</h5></div>
      <div class="ibox-content">
        <h1 class="no-margins"><%= number_with_precision @user_count, precision: 0, delimiter: ',' %></h1>
        <small>Total Users</small>
      </div>
    </div>
  </div>


  <div class="col-md-3 col-sm-6">
    <div class="ibox">
      <div class="ibox-title"><h5>Started</h5></div>
      <div class="ibox-content">
        <h1 class="no-margins"><%= number_with_precision @apps_count, precision: 0, delimiter: ',' %></h1>
        <small>Started Applications</small>
      </div>
    </div>
  </div>


  <div class="col-md-3 col-sm-6">
    <div class="ibox">
      <div class="ibox-title"><h5>Completed</h5></div>
      <div class="ibox-content">
        <h1 class="no-margins"><%= number_with_precision @apps_completed_count, precision: 0, delimiter: ',' %></h1>
        <small>Completed Applications</small>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6">
    <div class="ibox">
      <div class="ibox-title"><h5>Accepted</h5></div>
      <div class="ibox-content">
        <h1 class="no-margins"><%= number_with_precision @apps_accepted_count, precision: 0, delimiter: ',' %></h1>
        <small>Accepted Applications</small>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox">
      <div class="ibox-title">
        <h5>Applications</h5>

        <div class="pull-right">
          <%= bootstrap_form_tag url: dashboard_path, method: 'get' do |f| %>
              <div class="btn-group">
                <%= f.button 'Week', name: 'apps_time_filter', value: 'week', class: (@app_line_time_filter == 'week') ? 'btn btn-xs btn-white time-filter active' : 'btn btn-xs btn-white time-filter' %>
                <%= f.button 'Month', name: 'apps_time_filter', value: 'month', class: (@app_line_time_filter == 'month') ? 'btn btn-xs btn-white time-filter active' : 'btn btn-xs btn-white time-filter' %>
                <%= f.button 'Quarter', name: 'apps_time_filter', value: 'quarter', class: (@app_line_time_filter == 'quarter') ? 'btn btn-xs btn-white time-filter active' : 'btn btn-xs btn-white time-filter' %>
                <%= f.button 'Year', name: 'apps_time_filter', value: 'year', class: (@app_line_time_filter == 'year') ? 'btn btn-xs btn-white time-filter active' : 'btn btn-xs btn-white time-filter' %>
              </div>
          <% end %>
        </div>
      </div>
      <div class="ibox-content">
        <div class="row">
          <div class="col-md-9 m-b-sm">
            <%= area_chart dashboard_chart_data_path(type: 'created_and_completed', time_filter: @app_line_time_filter), library: {theme: 'maximized', isStacked: false, legend: {position: 'in', alignment: 'end'}} %>
          </div>
          <div class="col-md-3">
            <ul class="stat-list">
              <li>
                <h2 class="no-margins"><%= number_with_precision @user_filter_count, precision: 0, delimiter: ',' %></h2>
                <small>New Users in period</small>
                <div class="stat-percent">
                  <%= number_with_precision(@user_filter_count.fdiv(@time_filter_days), precision: 1, delimiter: ',') %>
                  / day
                </div>
              </li>
              <li>
                <h2 class="no-margins "><%= number_with_precision @apps_started_filter_count, precision: 0, delimiter: ',' %></h2>
                <small>Started in period</small>
                <div class="stat-percent">
                  <%= number_with_precision(@apps_started_filter_count.fdiv(@time_filter_days), precision: 1, delimiter: ',') %>
                  / day
                </div>
              </li>
              <li>
                <h2 class="no-margins "><%= number_with_precision @apps_completed_filter_count, precision: 0, delimiter: ',' %></h2>
                <small>Completed in period</small>
                <div class="stat-percent">
                  <%= number_with_precision(@apps_completed_filter_count.fdiv(@time_filter_days), precision: 1, delimiter: ',') %>
                  / day
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="ibox">
      <div class="ibox-title">
        <h5>Cohorts</h5>
      </div>
      <div class="ibox-content">
        <div class="row">
          <div class="col-md-2">
            <ul class="stat-list m-b-md">
              <li>
                <h2 class="no-margins"><%= @cohorts_active_count %></h2>
                <small>Active Cohorts</small>
              </li>
              <li>
                <h2 class="no-margins "><%= @cohorts_target_count %></h2>
                <small>Target Head Count</small>
              </li>
              <li>
                <h2 class="no-margins "><%= @cohorts_accepted_count %></h2>
                <small>Applicants Placed</small>
                <div class="stat-percent font-bold <%= @cohorts_accepted_pct >= 80 ? 'text-navy' : 'text-danger' %>">
                  <%= number_to_percentage(@cohorts_accepted_pct, precision: 0) %>
                </div>
                <div class="progress progress-mini">
                  <div style="width: <%= number_to_percentage(@cohorts_accepted_pct) %>" class="progress-bar"></div>
                </div>
              </li>
              <li>
                <h2 class="no-margins"><%= @cohorts_confirmed_count %></h2>
                <small>Confirmed Students</small>
                <div class="stat-percent font-bold <%= @cohorts_confirmed_pct >= 80 ? 'text-navy' : 'text-danger' %>">
                  <%= number_to_percentage(@cohorts_confirmed_pct, precision: 0) %>
                </div>
                <div class="progress progress-mini">
                  <div style="width: <%= number_to_percentage(@cohorts_confirmed_pct) %>" class="progress-bar"></div>
                </div>
              </li>
            </ul>
          </div>

          <div class="col-md-10">
            <div class="project-list table-responsive">
              <table class="table table-hover" id="cohorts-table">
                <tbody>
                <% @cohorts.each do |cohort| %>
                    <tr>
                      <td class="hidden-xs hidden-sm">
                        <%= cohort_status_label cohort.status %>
                      </td>
                      <td class="project-title">
                        <%= link_to cohort.name, cohort %>
                        <div class="hidden-xs">
                          <small><%= cohort.course.label %> <br /> <%= cohort_full_label cohort %>
                            <span class="hidden-sm">(<%= cohort_next_action_label cohort %>)</span></small>
                        </div>
                      </td>
                      <td class="project-completion hidden-xs">
                        <small>Accepted Applicants: <%= cohort.accepted_application_count %></small>
                        <div class="progress progress-mini">
                          <div style="width: <%= number_to_percentage(cohort.accepted_application_pct) %>" class="progress-bar"></div>
                        </div>
                      </td>
                      <td class="project-completion">
                        <small>Confirmed Students: <%= cohort.confirmed_application_count %></small>
                        <div class="progress progress-mini">
                          <div style="width: <%= number_to_percentage(cohort.confirmed_application_pct) %>" class="progress-bar"></div>
                        </div>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="ibox">
      <div class="ibox-title">
        <h5>Referral Source</h5>
      </div>
      <div class="ibox-content ">
        <%= pie_chart dashboard_chart_data_path(type: 'referral_source'), library: {theme: 'maximized'} %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="ibox">
      <div class="ibox-title">
        <h5>Payment Option</h5>
      </div>
      <div class="ibox-content ">
        <%= pie_chart dashboard_chart_data_path(type: 'payment_option'), library: {theme: 'maximized'} %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="ibox">
      <div class="ibox-title">
        <h5>Education</h5>
      </div>
      <div class="ibox-content ">
        <%= pie_chart dashboard_chart_data_path(type: 'education'), library: {theme: 'maximized'} %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/timeout.html.erb
<h1>Timeout test complete</h1>