config/routes.rb
Rails.application.routes.draw do


  # Public routes
  devise_for :users, :path => "applicant", controllers: {registrations: 'registrations'}, path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :apply

  # Admin routes
  devise_for :admins, :path => "admin", path_names: {sign_in: 'login', sign_out: 'logout'}
  scope '/admin' do

    resources :cohorts
    resources :admission_applications do
      member do
        patch 'workflow/:workflow_action', to: 'admission_applications#workflow', as: 'workflow'
      end
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :courses do
      resources :logic_questions, :profile_questions, except: :index
    end


    resources :admins, path: 'employees' do
      member do
        patch 'update_password'
        get 'edit_password'
      end
    end

    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/index', to: 'dashboard#index'
    get 'dashboard/chart/:type(/:time_filter)', to: 'dashboard#chart', as: 'dashboard_chart_data'

    get 'cohort/chart/:cohort_id/:type(/:time_filter)', to: 'cohorts#chart', as: 'cohort_chart_data'

    authenticated :admin do
      mount DelayedJobWeb, :at => "/delayed_job", via: [:get, :post]
    end

    # For testing various features
    get 'testing/timeout', to: 'testing#timeout'
    get 'testing/email', to: 'testing#email'
    get 'ping', to: 'testing#ping'

    root 'dashboard#index', as: :admin_root_path
  end

  get '/launch', to: 'home#launch'
  get '/live', to: 'home#live'
  get '/jobs', to: 'home#jobs'
  get '/volunteer', to: 'home#volunteer', as: 'volunteer'
  get '/catalog', to: redirect('/assets/documents/catalog.pdf')
  get '/conduct', to: redirect('/assets/documents/conduct_guide.pdf')
  get '/program', to: redirect('/assets/documents/program_description.pdf')

  root 'home#index'

end

app/views/admins/_edit_password_form.html.erb
<%= bootstrap_form_for(@admin, :url => { :action => "update_password" } ) do |f| %>
    <%= f.alert_message "Please fix the errors below." %>
    <%= f.password_field :password %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit 'Save', class: 'btn btn-primary btn-sm' %>
    <%= link_to 'Cancel', edit_admin_path(@admin), class: 'btn btn-link btn-sm' %>
<% end %>

app/views/admins/_form.html.erb
<%= bootstrap_form_for(@admin) do |f| %>
    <%= f.alert_message "Please fix the errors below." %>
    <%= f.text_field :email %>
    <%= f.text_field :first_name %>
    <%= f.text_field :last_name %>
    <%= f.select :status, ['Active','Inactive'] %>
    <%= f.submit 'Save', class: 'btn btn-primary btn-sm' %>
    <%= link_to 'Reset Password', edit_password_admin_path(@admin), class: 'btn btn-primary btn-sm' %>
    <%= link_to 'Cancel', admins_path, class: 'btn btn-link btn-sm' %>

<% end %>

app/views/admins/edit.html.erb
<% content_for :page_title, "Edit Employee :: #{@admin.name}" %>

<div class="ibox-content">
  <div class="row m-b-md">
    <div class="col-md-4">

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admins/edit_password.html.erb
<% content_for :page_title, "Change Password :: #{@admin.name}" %>

<div class="ibox-content">
  <div class="row m-b-md">
    <div class="col-md-4">
      <%= render 'edit_password_form' %>
    </div>
  </div>
</div>

app/views/admins/index.html.erb
<% content_for :page_title, "Employees" %>

<div class="ibox-content">
  <div class="table-responsive">
    <table class="table table-condensed table-striped table-bordered table-hover dataTable dtr-inline no-footer" id="admins-datatable">
      <thead>
      <tr>
        <th>Email</th>
        <th class="hidden-xs hidden-sm">Name</th>
        <th>Status</th>
        <th class="hidden-xs hidden-sm">Last Login</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @admins.each do |admin| %>
          <tr>
            <td><%= admin.email %></td>
            <td class="hidden-xs hidden-sm"><%= admin.name %></td>
            <td><%= admin.status %></td>
            <td class="hidden-xs hidden-sm"><%= admin.current_sign_in_at %></td>
            <td><%= link_to '<i class="fa fa-pencil"></i> Edit'.html_safe, edit_admin_path(admin), class: 'btn btn-sm btn-white' %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <br>

  <%= link_to 'New Employee', new_admin_path, {class: "btn btn-default btn-sm"} %>

</div>

app/views/admins/new.html.erb
<% content_for :page_title, "New Employee" %>

<div class="ibox-content">
  <div class="row m-b-md">
    <div class="col-md-4">

      <%= bootstrap_form_for(@admin) do |f| %>
          <%= f.alert_message "Please fix the errors below." %>
          <%= f.text_field :email, required: true %>
          <%= f.text_field :first_name, required: true  %>
          <%= f.text_field :last_name, required: true  %>
          <%= f.select :status, ['Active','Inactive'] %>
          <%= f.password_field :password, label: "New password", required: true %>
          <%= f.password_field :password_confirmation, label: "Confirm password", required: true %>
          <%= f.submit 'Save', class: 'btn btn-primary btn-sm' %>
          <%= link_to 'Cancel', admins_path, class: 'btn btn-link btn-sm' %>
      <% end %>

    </div>
  </div>
</div>