config/routes.rb
Rails.application.routes.draw do


  # Public routes
  devise_for :users, :path => "applicant", controllers: {registrations: 'registrations'}, path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :apply

  # Admin routes
  devise_for :admins, :path => "admin", path_names: {sign_in: 'login', sign_out: 'logout'}
  scope '/admin' do

    resources :cohorts
    resources :admission_applications do
      member do
        patch 'workflow/:workflow_action', to: 'admission_applications#workflow', as: 'workflow'
      end
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :courses do
      resources :logic_questions, :profile_questions, except: :index
    end


    resources :admins, path: 'employees' do
      member do
        patch 'update_password'
        get 'edit_password'
      end
    end

    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/index', to: 'dashboard#index'
    get 'dashboard/chart/:type(/:time_filter)', to: 'dashboard#chart', as: 'dashboard_chart_data'

    get 'cohort/chart/:cohort_id/:type(/:time_filter)', to: 'cohorts#chart', as: 'cohort_chart_data'

    authenticated :admin do
      mount DelayedJobWeb, :at => "/delayed_job", via: [:get, :post]
    end

    # For testing various features
    get 'testing/timeout', to: 'testing#timeout'
    get 'testing/email', to: 'testing#email'
    get 'ping', to: 'testing#ping'

    root 'dashboard#index', as: :admin_root_path
  end

  get '/launch', to: 'home#launch'
  get '/live', to: 'home#live'
  get '/jobs', to: 'home#jobs'
  get '/volunteer', to: 'home#volunteer', as: 'volunteer'
  get '/catalog', to: redirect('/assets/documents/catalog.pdf')
  get '/conduct', to: redirect('/assets/documents/conduct_guide.pdf')
  get '/program', to: redirect('/assets/documents/program_description.pdf')

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@cohorts = Cohort.current
  end
end

app/views/home/jobs.html.erb
<% content_for :head do %>

    <!-- FACEBOOK -->
    <meta property="og:url" content="<%= root_url %>" />
    <meta property="og:title" content="Prime Digital Academy Seeks Instructor" />
    <meta property="og:description" content="Prime is an intense, immersive 18-30 week training experience focused teaching people the fundamentals of software development through experiential learning and apprenticeship. Join the team and help train a new generation of developers." />
    <meta property="og:image" content="<%= asset_url("image-social-share.jpg") %>" />

    <!-- TWITTER -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@goprimeacademy" />
    <meta name="twitter:creator" content="@goprimeacademy">
    <meta name="twitter:title" content="Prime Software Engineering Academy Seeks Instructor" />
    <meta name="twitter:description" content="Prime is an intense, immersive 18-30 week training experience focused teaching people the fundamentals of software development through experiential learning and apprenticeship. Join the team and help train a new generation of developers." />
    <meta name="twitter:image:src" content="<%= asset_url("image-social-share.jpg") %>">

<% end %>

<h1>Help Train a New Generation of Software Engineers at Prime</h1>

<p>Prime Digital Academy is an 18 week accelerated learning program teaching foundational software engineering skills through a fullstack Javascript development curriculum. The 18 week program is supplemented by a hiring and apprenticeship network with dozens of companies signed up to bringing graduates of the program onboard to continue their learning on-the-job at an impressive list of the area’s best workplaces. Prime is distinguished from other programs through its tight connection with the industry. Founded by and co-located alongside 500+ employee custom software powerhouse, <%= link_to "The Nerdery", "http://nerdery.com" %>, Prime students get to learn the industry from the inside.</p>

<h2>Currently Seeking Software Engineer/Instructors</h2>

<p>Software Engineer/Instructors provide structure and ensure outcomes for students at Prime. Through experience, empathy and authority in the classroom they set the table for student learning, ensure all students are engaged and target resources, feedback and instruction based on individual need while focusing on excellent overall group outcomes.</p>

<p>We're looking for engineers who are passionate about education and mentorship. You'll be helping others learn the craft of software development using modern tools and techniques (especially Javascript). As an instructor, you'll be a teacher, a team leader, a coach and a mentor for a cohort of students during their time at Prime. You'll work with a partner, team teaching in the classroom to guide 20 students through the Prime program as they begin their careers as developers. You'll work with your students as they tackle both coursework you help to create and projects that they're working on for local startups.</p>

<p>You'll be joining a small company with a passionate, dedicated team backed by one of the most successful and fastest growing software development firms in the country. We're looking for a person who shares <%= link_to "our values", "/#about" %> and will help us shape our future.</p>

<p>We offer competitive salary and benefits including a generous PTO program, medical, dental and vision benefits as well as a 401K plan with a company match.</p>

<p>Details and functional job description are below. To apply, send your resume and a letter telling us about yourself at <%= mail_to "recruiting@primeacademy.io","recruiting@primeacademy.io", subject: "Instructor Position Application" %>.</p>

<div class="jobs-column">

<h3>Accountability</h3>

<p>Instructors at the Academy are accountable for:</p>

<ul>
	<li>Effective instruction</li>
	<li>Student participation</li>
	<li>Prework monitoring</li>
	<li>Regular student 1:1s</li>
	<li>Alumni support</li>
	<li>Direct mentors</li>
	<li>Student selection and cohort building</li>
</ul>

<h3>Typical Duties and Responsibilities</h3>

<p>Responsibilities include:</p>

<ul>
	<li>Leading daily lectures</li>
	<li>Supporting students in the classroom through ad hoc instruction and advice</li>
	<li>Engaging students in classroom activities</li>
	<li>Moderating class discussion to balance input and participation</li>
	<li>Weekly pre-work hangouts with cohorts in the pre-work phase</li>
	<li>Scheduling and leading 1:1 sessions with students</li>
	<li>Providing feedback on student code</li>
	<li>Participate in bi-weekly alumni “office hours”</li>
	<li>Respond to correspondence from current students and alumni through email and instant messaging</li>
	<li>Provide direction to mentors in the classroom</li>
	<li>Set schedule for instruction, coordinating with cohort mentor</li>
	<li>Review student applications</li>
	<li>Perform prospective student interviews</li>
	<li>Select students within program guideline to compose cohorts</li>
</ul>

<h3>Reporting Relationships</h3>

<p>Instructors are responsible for student outcomes in the classroom, providing direction to mentors working in the classroom to ensure a coordinated approach. Instructors are directly supervised by the President. Instructors work on a peer basis with curriculum development staff to customize and iterate on coursework.</p>

</div>

<div class="jobs-column">

<h3>Skills and Qualifications</h3>
<ul>
	<li>Expertise in modern software engineering technology, tools and techniques</li>
	<li>Expertise in HTML, CSS and Javascript</li>
	<li>Expertise in Javascript-based frameworks and tools like Node, Angular and Express</li>
	<li>Expertise in data structures in SQL and NoSQL databases</li>
	<li>Expertise in modern source code management, utility and deployment technologies like Grunt, Bower and Git</li>
	<li>Deep understanding of project management, user experience and quality assurance principles as they relate to software engineering</li>
	<li>Experience lecturing and delivering talks on technical subjects</li>
	<li>Experience mentoring software engineers</li>
	<li>Excellent written and verbal communication skills</li>
	<li>Independent, self-motivated, and success driven</li>
	<li>Manage difficult or emotional situations, responding promptly to requests for service and assistance</li>
	<li>Proven leadership and teamwork skills and collaborative group problem solving</li>
	<li>Organized, detail oriented, and great at follow-through</li>
	<li>Must have the ability to multi-task in a fast paced and dynamic environment</li>
</ul>

<h3>Education and Experience</h3>

<ul>
	<li>3 or more years of experience in software development</li>
	<li>2 or more years of experience teaching or mentorship in the workplace</li>
</ul>

<h3>Working Conditions</h3>
<ul>
	<li>General office setting—no hazardous chemicals or manufacturing equipment/production lines/machinery, however, noise levels fluctuate with open office environment</li>
	<li>Minimal travel</li>
	<li>Sitting\standing (75%) of the day at meetings and at desk</li>
	<li>Lecturing (15%)</li>
	<li>Keyboarding and using mouse (90%)</li>
	<li>Occasional stooping and reaching (5%)</li>
	<li>Reading (90%)</li>
</ul>
</div>

<h2 class="jobs-header-interested">Interested?</h2>
<p>If you've gotten this far down the page and you're still excited about joining the team, we'd love to meet you. To apply, please send your resume and a letter telling us about yourself at <%= mail_to "recruiting@primeacademy.io","recruiting@primeacademy.io", subject: "Instructor Position Application" %>.</p>

app/views/home/launch.html.erb
<p>FOR IMMEDIATE RELEASE</p>

<p>Contact:<br/>
Mark Hurlburt, 612-222-8108, <%= mail_to "press@primeacademy.io", "press@primeacademy.io", encode: "javascript" %><br/>
Mark Malmberg, 612-850-3178, <%= mail_to "markm@nerdery.com", "markm@nerdery.com", encode: "javascript" %></p>

<h2>The Nerdery Launches Prime Digital Academy to Produce Homegrown Software Engineers and Web Developers</h2>

<h3>Prime’s partnerships with industry and local government aim to fuel innovation and economic development in the region while creating sustainable solution to the coding talent crunch</h3>

<p>Minneapolis - (December 15, 2015) - Twin Cities-based custom software company The Nerdery today announced its launch of Prime Digital Academy (Prime), a school for software engineers. Prime is accepting applications from prospective students today at <%= link_to "http://primeacademy.io", "http://primeacademy.io" %> for its beta cohort starting March 3.</p>

<p>“While The Nerdery’s inspiration for creating Prime stems from our own neverending business need for software engineers, we’re further encouraged by the growing number of supporting organizations who share our interests in priming next generations of tech talent,” said Mike Derheim, CEO and co-founder of The Nerdery. “Nearly 30 companies and organizations have committed to hire graduates, host apprenticeships, or serve on Prime’s curriculum board. From the start of our conversations with partners throughout our community it was clear that this school’s impact can help companies industry-wide – this is bigger than us.”</p> 

<p>Local companies onboard with Prime include: 3M; Ackmann & Dickenson; AIC; AVL Growth Partners; BIR Networks; BustOut Solutions; Carlson School Center for Entrepreneurship; Digital People; Genesis 10; GovDelivery; ICS Consulting; Livefront; MN Cup; MN.IT; Modern Climate; Morsekode; Myriad Mobile; Olson; Periscope; PH Digital Labs; Robert Half Technology; Smart Factory; Software For Good; Sport NGIN; Target; Thomson Reuters; and When I Work.</p>

<p>Prime will feature an intense, immersive accelerated learning program dedicated to helping smart, driven learners get up to speed for entry-level jobs in software engineering. The academy focuses on industry-led experiential learning and apprenticeship with some of the metro’s leading IT employers. After its first cohort this spring, Prime will start admitting regular monthly cohorts in July of 2015. Tuition for the academy is set at $12,500. Applications for the first cohort will close on January 22.</p> 

<p>“This is another important step in training and developing our state’s highly skilled workforce,” said Margaret Anderson Kelliher, president and CEO of the Minnesota High Tech Association.  “We were happy to see a local company step forward, ready and willing to provide this training. It’s something that will benefit Minnesota and our people now and well into the future.”</p>

<p>To encourage more women to pursue tech careers, The Nerdery and Modern Climate will each grant a $500 scholarship to each female applicant accepted into the program, providing a $1,000 total scholarship to women training as software engineers. Digital People will grant a $500 scholarship for the first 5 veterans accepted into the program in 2015.</p>

<p>Prime is partnering with City of Minneapolis Employment Training, the Minnesota High Tech Association,  the Creating IT Futures Foundation and Jewish Family and Children’s Service of Minneapolis to increase the accessibility of the program to all Minnesotans by making public and private funding available for qualifying students who would be otherwise unable to attend. This partnership is part of a program by the White House Office of Science and Technology Policy to foster development of the accelerated-learning model in communities nationwide.</p> 

<p>“The Minneapolis-Saint Paul region has traditionally been a hub for innovation. Ingenious startups have found that our cities provide the environment and the labor force to make companies like 3M, Medtronic, and others successful,” said Minneapolis Mayor Betsy Hodges. “In this fast, technology-driven environment, we need to work together to make it easy for every individual to acquire the skills that meet the demands of our growing high-tech industry. I am very excited for this partnership and for the results that Prime Digital Academy will bring.”</p>

<p>Minnesota businesses already feel the competition for too few talented, job-ready software developers – 65% of IT leaders say the tech talent gap is negatively affecting their business. Industry analysts see jobs in application development increasing by 28% through 2020.</p> 

<p>“Thomson Reuters has a vested interest in helping to engage today’s students with a life-long passion for technology so that we can help foster a skilled workforce for tomorrow,” said Lisa Schlosser, Chief Technology Officer of FindLaw, a Thomson Reuters business. “That’s why it is a priority for us to support training programs – such as our own Python and Java coding classes for middle school students, and Prime’s technology education for adult learners – that help ensure a vibrant, dynamic community that can benefit and sustain Minnesota’s economy.”</p>

<p>Prime’s 18-week program’s objective (with optional 12-week or more apprenticeship) is to arm graduates with three things: 1) entry-level technical skills relevant in the current market, 2) behavioral skills to succeed as part of a software development team, 3) a mindset of continuous learning and toolbox of techniques to support a long, successful career. Prime’s President Mark Hurlburt sums up the business’ objective: “Prime is about changing our students lives for the better while at the same time serving the tech community in Minnesota.” Hurlburt was The Nerdery’s CSO before “leaving” to lead Prime Digital Academy.</p>

<p>Prime’s staffing model reflects its commitment to community partnership. Students are grouped into cohorts of 18-20 individuals, with each cohort staffed by a team of one instructor (a full-time employee of the school) and one full-time mentor (a working software developer on a sabbatical from a local company, their salary covered by Prime during their stay). “It’s unconventional, but we see it as a win for everyone,” said Hurlburt. “The students get up-to-the-minute current context from working professionals, the mentors get build their coaching and leadership skills, and mentor’s employers get professional development for their employee and an inside track on two cohorts of entry-level candidates that will have learned to think a lot like one of their star performers.”</p>

<p>“Software engineers are at the heart of GovDelivery’s business, and Prime’s program is an innovative solution to developing more of them the Minnesota way – by tapping the amazing talent pool we already have,” said Scott Burns, CEO & Co-Founder, GovDelivery. “We believe Prime can connect hundreds of new people with rewarding careers in technology and that it will be a competitive asset to our business and the State of Minnesota.”</p>

<p>“Everything about Prime is aimed at helping our students make a smooth transition into their new lives as professional software engineers,” said Derheim. “Being able to study software engineering from within a working software development company is a great way to help students acclimate and really learn the industry from the inside.”</p>

<p>The school’s proximity to The Nerdery – and the involvement of industry professionals in mentoring and job assistance – will afford students an education opportunity unlike anything currently available to students in Minnesota. But students’ industry experience will extend outside the walls of The Nerdery and Prime. Many students will get the chance apply these skills immediately through a network of paid apprenticeships Prime will coordinate with local tech employers. These apprenticeships offer students a chance to gain critical on-the-job experience for their resumes, while employers get a chance to evaluate their talent and assess if they’d be a good fit for their team.</p> 

<p>“What excites us about Prime is their passion for truly preparing new developers for the realities of the tech industry,” said Chad Halvorson, CEO/founder of When I Work. “The disciplines and expectations that Prime instills with graduates is what's been missing from traditional academic tech programs.”</p>

<p>Prime expects to continue to grow its partner network. “We’d love to someday have every Minnesota employer who depends on software engineers involved in our program in some way,” said Hurlburt. “We see the talent gap in software as a problem the whole industry needs to pull together in order to solve.”</p> 

<h3>More comments from some of Prime’s partners:</h3>
<p>“Finding and nurturing young technical talent has always been a huge challenge for digital agencies,” said Mark Morse, CEO/Chief Creative Officer, Morsekode. “We believe Prime will create a highly-desirable level of candidate that can not only fill these workforce needs, but begin to shape the future of the workforce itself.”</p>

<p>“The software industry is perpetually evolving, so learning and teaching are always a primary endeavor for anybody in this industry,” said Jeff Lin, Founder, Bust Out Solutions. “Prime brings this to the forefront.”</p>

<p>“Prime is a program that makes an immediate impact by coaching, training and providing hands on relevant projects based on real workplace criteria that will turn out market-ready students,” said Bryan Peglow, Business Development Manager at Digital People. “There are a lot of talented people out there that just need some additional skills under their belt and Prime will bridge that gap.”</p>

<p>“At Software for Good, we've had great successes hiring development bootcamp graduates,” said Casey Helbing, founder of Software for Good. “These programs give students working knowledge of what it takes to be a successful Software Developer on day one. It is great to see a bootcamp coming to Minnesota.”</p>

<p>“Prime provides our company with immediate access to qualified technical resources and fills the current skills-gap that exists in the market today,” said Kyle Meehan, co-founder/Strategy Director, PH Digital Labs.</p>

<p>“We're happy to be aligned with Prime's goal of creating software engineering opportunities for individuals and growing the industry via the development of skills and knowledge through hands-on experience," said Justin Royer, Vice President of Digital Engagement at Periscope.</p>

<p>“AIC is very excited to partner with Prime Academy,” said James Brown, Managing Director of AIC. “We look forward to helping students prepare for their careers in software engineering. Our partnership with Prime Digital Academy will help boost the Twin Cities tech industry by connecting  graduates to immediate job opportunities that fit their skills from the excellent curriculum that Prime has developed.”</p>

<p>“The market has been very tight for the Software Development arena, and we are eager to partner with Prime to elevate and strengthen the candidacy of entry-level Software Engineers,” said Jacqueline Snyder at Infinity Consulting Services. “It is an honor to collaborate so closely with Prime and we look forward to the evolution of the Tech community in Minnesota as a result of this initiative.”</p>

<p>"We see Prime’s program as a modern approach to enabling students to successfully navigate getting started in a relatively complex and high-demand career path,” said John Moberg, CIO, Modern Climate. “Prime has reinvented an accelerated learning program to provide a win-win situation fostering students-first and network-first benefit. We’re excited to be a part of this endeavor to raise the bar for the greater good." </p>

<h3>About Prime Digital Academy</h3>
<p>Prime Digital Academy aims to build a new model for education that works at the speed of the software industry. The intense, immersive 18 week accelerted learning program transforms students' lives by empowering them with the skills and mindset to build a meaningful career in software development. Prime's meaningful connection with the industry, its unique instruction model that brings working developers into the classroom as mentors and its focus on experiential learning and apprenticeship set it apart from other training programs. Prime's network of partners organizations that inform curriculum, host apprenticeship and hire graduates includes 30 companies ranging from innovative startups to Fortune 500 household names.</p>


<h3>About The Nerdery</h3>
<p>Founded by three programming pioneers in 2003, The Nerdery is professional home of 500+ web developers, UX designers, QA engineers and other Nerds creating custom interactive technology to solve clients’ unique business needs, including websites, mobile and social-media app development. The Nerdery has made Inc. Magazine’s list of fastest growing private companies for seven straight years, appeared on multiple top workplace lists, and received Inc.’s Hire Power Award for year-to-year job growth. Through The Nerdery Overnight Website Challenge, volunteer web pros have donated about $5 million in pro bono services to 144 nonprofits. The Nerdery marked its 10th anniversary in 2013 by launching a commemorative coin etched with company core values and vision into space.</p>

<p>- ### -</p>

app/views/home/live.html.erb
<div class="section-hangout-cta">
	<%= link_to "RSVP FOR FEBRUARY 27th","https://plus.google.com/b/109023548423120875193/events/carovi00b5h851u9p34vj8vq41k", class: "button" %>	
	<%= link_to "RSVP FOR MARCH 27th","https://plus.google.com/b/109023548423120875193/events/c62gu4o7jrel4ujvcpsg0vrouj0", class: "button" %>	
</div>

<h1>Get live answers from Prime.</h1>
<p>Join us for a Google Hangout with Prime staff and get answers to any questions you may have about Prime. Submit your questions ahead of time or join the hangout live to participate. You can watch the previous sessions below.</p>
<p>Burning questions that can't wait? Call us at (952) 222-8108 or <%= mail_to "hello@primeacademy.io", "drop us an email", encode: "javascript" %>.</p>


<iframe width="940" height="500" src="https://www.youtube.com/embed/RP6BIsFOt3s" frameborder="0" allowfullscreen class="hangout-video"></iframe>
<iframe width="940" height="500" src="https://www.youtube.com/embed/IQr-3ZVnTcg" frameborder="0" allowfullscreen class="hangout-video"></iframe>
<iframe width="940" height="500" src="https://www.youtube.com/embed/pl988Q_0p6A" frameborder="0" allowfullscreen class="hangout-video"></iframe>
<iframe width="940" height="500" src="https://www.youtube.com/embed/I-PpsFC0b5A" frameborder="0" allowfullscreen class="hangout-video"></iframe>

app/views/home/volunteer.html.erb
<% content_for :head do %>

    <!-- FACEBOOK -->
    <meta property="og:url" content="<%= volunteer_url %>" />
    <meta property="og:title" content="Prime Digital Academy - Volunteer as a mentor or a guest speaker." />
    <meta property="og:description" content="Prime is looking for software developers in Minnesota who want to share their passion with our students. Volunteer as a mentor (10 hours over 3 months) or a guest speaker/panelist (as little as 1 hour, 1 time)." />
    <meta property="og:image" content="<%= asset_url("image-social-volunteer-share.jpg") %>" />

    <!-- TWITTER -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@goprimeacademy" />
    <meta name="twitter:creator" content="@goprimeacademy">
    <meta name="twitter:title" content="Volunteer at Prime Academy" />
    <meta name="twitter:description" content="Prime is looking for software developers in Minnesota who want to share their passion with our students. Volunteer as a mentor (10 hours over 3 months) or a guest speaker/panelist (as little as 1 hour, 1 time)." />
    <meta name="twitter:image:src" content="<%= asset_url("image-social-volunteer-share.jpg") %>">

<% end %>

<h1>Volunteer To Help Someone Code Tomorrow</h1>
<p>Interested in supporting emerging talent in Minnesota's tech community? Prime Digital Academy is looking for local software professionals to help develop entry-level newcomers. We look forward to introducing you to our group of dedicated beginners that are eager to learn from your experiences and perspectives. We're currently seeking speakers/panelists and volunteer mentors but if you had something else in mind you can reach out to us at <%= mail_to "community@primeacademy.io", "community@primeacademy.io", encode: :javascript %> to share your ideas for getting involved. Thanks for your support!</p>

<div class="volunteer-column">
<h3>Be A Speaker or Panelist</h3>
<p>Minnesota's tech industry is full of smart, talented people. We're looking for some friendly volunteers to share their knowledge and passion though talks, panel discussions and Q&amp;A's at Prime. Ideally, talks should reinforce some of the nuts and bolts of development, but we're also on the lookout for a few inspiring or engaging topics outside of programming (e.g., starting my first company, completing an Ironman triathlon, etc.).Presentations can be any format: slide decks, activities, discussion-based, etc.</p>
<p>We're also interested in volunteers willing to populate expert roundtables, free-form "AMA-style" sessions and other low-commitment ways to bring their expertise into the classroom. Whether you're interested in helping students understand continuous integration or you just want to show them the secret to solving a Rubick's cube really, really quickly, register to volunteer by telling us the things you're passionate about and we'll follow up with you and find a way to connect you with our students.</p>

<p><%= link_to "Volunteer as a Speaker", "https://docs.google.com/a/nerdery.com/forms/d/1IaZEZAmtPKpkfF1AfJ9d-214XjF3Tu0beMBNOB4Keno/viewform", class: "button" %></p>
</div>


<div class="volunteer-column">
<h3>Be A Volunteer Mentor</h3>
<p>Mentoring is a fun way to help a small group of students orient themselves as they get started in the software development industry. You and a few other working developers (your friends if you wanted to volunteer together) will be matched with a handful of students. We're teaching them to code, your job as mentor is to get to know them and have conversations about the craft and the industry. Bring your experience, a “pay-it-forward” attitude, a genuine interest in connecting with others, and about 10 hours of your time over three months. Students will bring questions and handle all the meeting logistics.</p> 
<p>You'll attend orientation where you’ll meet your group. After that introduction, you’ll have 5 meetings over the next three months. The format is up to you and your group - book club, beers, video games or just hanging out. The important thing is that you’re sharing your stories and perspective. You’re welcome to connect with students over email, social media and IM if you want; just set boundaries that work for you.</p>
<p><%= link_to "Volunteer as a Mentor", "https://docs.google.com/a/nerdery.com/forms/d/1pyVwoTOBzJHL0-hQJ25gZIH5H2sY3s8vYdFDeHEs3P0/viewform", class: "button" %></p>
</div>

<div class="sidebar-students">
<h3>Who are our students?</h3>
<p>Prime Academy students are highly-motivated beginners who are diving head first into a full-stack javascript development curriculum. Our students have a range of inspiring backgrounds and have been selected by our admissions as intelligent, professional and passionate about learning. Students range in age from recent high school graduates to people embarking on their second (or third) act careers. Our student population has a roughly even gender split and while we have students as young as 19 and as old as 60, about 70% of them are between the ages of 20 and 40.</p>
</div>